In [2]:
import pandas as pd
import os
import re
import datetime
import sys
from os import listdir
from datetime import date
import glob
import numpy as np

ModuleNotFoundError: No module named 'pandas'

# Media

In [2]:
#get a list with all the paths of all files
root = "/Users/davidblancoherrero/Documentos/Proyecto tripol/DESCARGA_MEDIOS" # it may have many subfolders and files inside
lst = []
from fnmatch import fnmatch
pattern = "*.txt"      #I want to get only txt files 
#pattern = "*.*"        # Note: Use this pattern to get all types of files and folders 
for path, subdirs, files in os.walk(root):
    for name in files:
        if fnmatch(name, pattern):
            lst.append((os.path.join(path, name)))
files = pd.DataFrame({"filePaths":lst})
files.to_csv("filepaths.csv")
files['filePaths']
#files = files.values.tolist()

files

                                              filePaths
0     /Users/carlosarcila/Dropbox/Development/tripol...
1     /Users/carlosarcila/Dropbox/Development/tripol...
2     /Users/carlosarcila/Dropbox/Development/tripol...
3     /Users/carlosarcila/Dropbox/Development/tripol...
4     /Users/carlosarcila/Dropbox/Development/tripol...
...                                                 ...
8640  /Users/carlosarcila/Dropbox/Development/tripol...
8641  /Users/carlosarcila/Dropbox/Development/tripol...
8642  /Users/carlosarcila/Dropbox/Development/tripol...
8643  /Users/carlosarcila/Dropbox/Development/tripol...
8644  /Users/carlosarcila/Dropbox/Development/tripol...

[8645 rows x 1 columns]

In [62]:
#Read file from line 2 and split into paragraphs to a list

def transform_to_paragraphs (filename):
    

    with open(filename) as f:
        country=f.name[f.name.rindex('/')+1:f.name.rindex('/')+3]
        reference=f.name[f.name.rindex('/')+1:]
        lines = f.read()

        tests = lines.split("\n\n")
        match = re.search(r'\d{2}/\d{2}/\d{4}', tests[0])
        try:
            date = datetime.datetime.strptime(match.group(), '%d/%m/%Y').date() 
        except AttributeError:
            return "NaN"
        except ValueError:
            return "NaN"
        try:
            media = tests[0].split(". ",1)[1]
        except IndexError:
            return "NaN"

        df = pd.DataFrame(tests[2:])
        df.rename(columns={0:'text'}, inplace=True)
        df['date']=date
        df['media']=media
        df['country']=country
        df['reference']=reference
        df.to_csv(r'data/'+f'{reference}.csv')

In [63]:
for i in files['filePaths']:
    transform_to_paragraphs(i)

In [64]:
def prepend(list, str):
    str += '{0}'
    list = [str.format(i) for i in list]
    return(list)

filepaths = [f for f in listdir("./data") if f.endswith('.csv')]
str = 'data/'
filepaths = prepend(filepaths, str)
df = pd.concat(map(pd.read_csv, filepaths))

print("Number of files: ", len(filepaths))
print("Number of records: ", len(df))

Number of files:  8596
Number of records:  75934

In [65]:
df.sort_values(by=['date']).tail(50)

,Unnamed: 0,text,date,media,country,reference
6,6,Cabe observar finalmente cómo algunos procedim...,2022-01-06,EL MERCURIO,CH,CH_MER_06_01_22_1A.txt
6,6,Las oportunidades,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
5,5,"Sin embargo, y a pesar de los esfuerzos, tal c...",2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
4,4,La necesidad de construir soberanía tecnológic...,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
3,3,La Celac cobró importancia durante la pandemia...,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
1,1,Analisemos a substância e a causalidade desta ...,2022-01-06,DIARIO DE NOTICIAS,PO,PO_DIA_06_01_22_3B.txt
2,2,Para percebermos as causas motoras desta manob...,2022-01-06,DIARIO DE NOTICIAS,PO,PO_DIA_06_01_22_3B.txt
2,2,Cuando el gobierno del presidente López Obrado...,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
1,1,"Entre 2017 y 2019, el bloque regional atravesó...",2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
0,0,México termina su presidencia pro témpore (PPT...,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
6,6,"Son previsibles, en este escenario, las fricci...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3C.txt
5,5,No olviden que la Ley Trans ya se celebró como...,2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3C.txt
0,0,Há um ano um presidente em exercício de funçõe...,2022-01-06,DIARIO DE NOTICIAS,PO,PO_DIA_06_01_22_3A.txt
4,4,Como lo he venido exponiendo hace mucho tiempo...,2022-01-06,COOPERATIVA,CH,CH_COO_06_01_22_3A.txt
5,5,\n,2022-01-06,COOPERATIVA,CH,CH_COO_06_01_22_3A.txt
0,0,"«Non sono il tipico politico», è la prima riga...",2022-01-06,CORRIERE DELLA SERA,IT,IT_COR_06_01_22_3D.txt
1,1,Nell’epoca delle ribellioni più assurde contro...,2022-01-06,CORRIERE DELLA SERA,IT,IT_COR_06_01_22_3D.txt
5,5,Cuanto sucedió en Estados Unidos desde que el ...,2022-01-06,EL PERIODICO,SP,SP_PER_06_01_22_1A.txt
5,5,Era desejável que mais Portugal pudesse estar ...,2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3B.txt
4,4,Conquista-se ascendente político por via da di...,2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3B.txt
3,3,"É, de resto, neste quadro de enorme vacuidade ...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3B.txt
0,0,Ni es un cambio sin precedentes en el mercado ...,2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
3,3,"De grande alcance, os normativos que prevêem a...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3A.txt
2,2,Prosseguindo o objectivo de travar e conter em...,2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3A.txt
1,1,"Sob o lema Pacote anticorrupção, o diploma con...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3A.txt
18,18,Tal vez la pregunta por el carácter socialdemó...,2022-01-06,EL MOSTRADOR,CH,CH_MOS_06_01_22_3F.txt
0,0,"Recuperando o tema da corrupção, sinteticament...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3A.txt
8,8,El ejercicio de la presidencia de la Celac per...,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
7,7,Desde la creación de Celac en 2011 se establec...,2022-01-06,PAGINA 12,AR,AR_PAG_06_01_22_3A.txt
0,0,La decisione del giudice di Helsinki dovrebbe ...,2022-01-06,CORRIERE DELLA SERA,IT,IT_COR_06_01_22_3C.txt
1,1,È la prima volta che si assiste in Europa a un...,2022-01-06,CORRIERE DELLA SERA,IT,IT_COR_06_01_22_3C.txt
2,2,"Le diseguaglianze, e l’incapacità di fermare l...",2022-01-06,CORRIERE DELLA SERA,IT,IT_COR_06_01_22_3C.txt
3,3,E se il reclutamento dei bambini può apparire ...,2022-01-06,CORRIERE DELLA SERA,IT,IT_COR_06_01_22_3C.txt
0,0,Os mais saudosos recorrem à RTP Memória para e...,2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3B.txt
17,17,En los años de la UP la pregunta era otra. El ...,2022-01-06,EL MOSTRADOR,CH,CH_MOS_06_01_22_3F.txt
1,1,"O de intervir e, sobretudo, o de ouvir. Espera...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3B.txt
1,1,Esto ya se evidencia en las grandes incautacio...,2022-01-06,COOPERATIVA,CH,CH_COO_06_01_22_3A.txt
2,2,"Es en consideración de estos antecedentes, que...",2022-01-06,COOPERATIVA,CH,CH_COO_06_01_22_3A.txt
3,3,Estamos ante un nuevo escenario del narcotráfi...,2022-01-06,COOPERATIVA,CH,CH_COO_06_01_22_3A.txt
7,7,"Dicho queda: calidad en el empleo, agilidad de...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
6,6,"En cuanto a los contratos, a partir de ahora s...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
1,1,"Nunca se viram tantos títulos com ""pode"". É o ...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3C.txt
0,0,Se pandemia trouxe para a ribalta virologistas...,2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3C.txt
5,5,"Los empleados afectados, percibirán una presta...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
4,4,"La Reforma Laboral 2020, de momento, impacta e...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
3,3,"Y no está mal, solo que nuestro mercado adolec...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
2,2,"Ahora bien, hemos cerrado 2021 con un paro reg...",2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
1,1,El Gobierno ha aprobado “in extremis” la Refor...,2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3B.txt
2,2,"Os debates televisivos servem, sobretudo, para...",2022-01-06,JORNAL DE NOTICIAS,PO,PO_JOR_06_01_22_3B.txt
13,13,"Na sexta-feira, todos os órgãos de comunicação...",2022-01-06,SAPO,PO,PO_SAP_06_01_22_3B.txt

In [66]:
df['country'].unique()

array(['IT', 'CH', 'AR', 'SP', 'PO', ' A', ' I', ' P', ' S', ' C'],
      dtype=object)

In [67]:
df['country'] = df['country'].str.replace(' P','PO')
df['country'] = df['country'].str.replace(' A','AR')
df['country'] = df['country'].str.replace(' I','IT')
df['country'] = df['country'].str.replace(' S','SP')
df['country'] = df['country'].str.replace(' C','CH')

In [68]:
df.isnull().sum()

Unnamed: 0      0
text          805
date            0
media           0
country         0
reference       0
dtype: int64

In [69]:
df[df['text'].isna()]

,Unnamed: 0,text,date,media,country,reference
11,11,NaN,2021-02-25,EL MOSTRADOR,CH,CH_MOS_25_02_21_1A.txt
5,5,NaN,2021-11-26,EL PERIODICO,SP,SP_PER_26_11_21_1B.txt
7,7,NaN,2020-11-06,PUBLICO,PO,PO_PUB_06_11_20_3C.txt
9,9,NaN,2020-11-06,PUBLICO,PO,PO_PUB_06_11_20_3C.txt
16,16,NaN,2021-10-11,SAPO,PO,PO_SAP_11_10_21_3C.txt
...,...,...,...,...,...,...
8,8,NaN,2021-06-20,EL CONFIDENCIAL,SP,SP_CON_20_06_21_3D.txt
5,5,NaN,2021-01-09,EL MUNDO,SP,SP_MUN_09_01_21_3A.txt
7,7,NaN,2020-11-02,EL MERCURIO,CH,CH_MER_02_11_20_3B.txt
6,6,NaN,2021-06-09,PUBLICO.ES,SP,SP_PUB_09_06_21_3A.txt
4,4,NaN,2021-01-30,JORNAL DE NOTICIAS,PO,PO_JOR_30_01_21_3A.txt

In [70]:
df.dropna(inplace=True)
df[df['text'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, text, date, media, country, reference]
Index: []

In [71]:
df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d")

In [72]:
df

,Unnamed: 0,text,date,media,country,reference
0,0,"Siccome s’era capita l’aria, quel gran genio d...",2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt
1,1,E per essere interessante anziché riabilitato ...,2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt
0,0,di Giancarlo Mazzuca,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt
1,1,SOS giovani. Se il Covid ha continuato a prend...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt
2,2,Le cifre parlano chiaro perché in Italia oltre...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt
...,...,...,...,...,...,...
5,5,Quienes vivimos la Transición podemos dar test...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt
6,6,La frustración y fragmentación social provocad...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt
7,7,"Por lo demás, el acoso de la extrema derecha c...",2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt
8,8,En un ambiente así resultaría lógico poner un ...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt
9,9,Aunque me gustaría equivocarme en la predicció...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt

In [21]:
df['date']

0   2021-04-29
1   2021-04-29
0   2021-01-25
1   2021-01-25
2   2021-01-25
       ...
5   2021-05-03
6   2021-05-03
7   2021-05-03
8   2021-05-03
9   2021-05-03
Name: date, Length: 75129, dtype: datetime64[ns]

In [73]:
df['lang']=df['country']
df['lang'] = df['lang'].str.replace('IT','it')
df['lang'] = df['lang'].str.replace('CH','es')
df['lang'] = df['lang'].str.replace('AR','es')
df['lang'] = df['lang'].str.replace('SP','es')
df['lang'] = df['lang'].str.replace('PO','pt')

In [14]:
#df.loc[df['country'] == " P"]

In [75]:
df.to_csv('media_database_tripol.csv', index=False)

In [76]:
df.sort_values(by="date")

,Unnamed: 0,text,date,media,country,reference,lang
7,7,El gran reseteo anunciado en Davos (esa oportu...,2020-05-27,EL ESPAÑOL,SP,SP_ESP_27_05_21_3B.txt,es
3,3,Que Sánchez ofrezca concordia irrita: ¡queremo...,2020-05-27,LA VANGUARDIA,SP,SP_VAN_27_05_21_3B.txt,es
5,5,–¡Queremos confirmar nuestros prejuicios y nue...,2020-05-27,LA VANGUARDIA,SP,SP_VAN_27_05_21_3B.txt,es
6,6,Manifestación de la ANC el 16 de mayo en Barce...,2020-05-27,LA VANGUARDIA,SP,SP_VAN_27_05_21_3B.txt,es
7,7,Para seguir haciendo sopa boba de pescado de u...,2020-05-27,LA VANGUARDIA,SP,SP_VAN_27_05_21_3B.txt,es
...,...,...,...,...,...,...,...
1,1,zkia Siches jugó un rol clave en el triunfo de...,2022-01-06,LA TERCERA,CH,CH_TER_06_01_22_3B.txt,es
15,15,"La pregunta es si, en estas condiciones, se pu...",2022-01-06,EL MOSTRADOR,CH,CH_MOS_06_01_22_3E.txt,es
14,14,"Sin control real, los fondos de inversión priv...",2022-01-06,EL MOSTRADOR,CH,CH_MOS_06_01_22_3E.txt,es
4,4,Que impacto terão as revoluções digital e ener...,2022-01-06,DIARIO DE NOTICIAS,PO,PO_DIA_06_01_22_3A.txt,pt
2,2,Algunos de esos planes prioritarios de la form...,2022-01-06,LA RAZON,SP,SP_RAZ_06_01_22_3C.txt,es

# tweets

In [33]:
#get a list with all the paths of all files
root = "/Users/davidblancoherrero/Documentos/Proyecto tripol/DESCARGA_TWEETS" # it may have many subfolders and files inside
lst = []
from fnmatch import fnmatch
pattern = "*.csv"      #I want to get only txt files 
#pattern = "*.*"        # Note: Use this pattern to get all types of files and folders 
for path, subdirs, files in os.walk(root):
    for name in files:
        if fnmatch(name, pattern):
            lst.append((os.path.join(path, name)))
files = pd.DataFrame({"filePaths":lst})
files.to_csv("filepaths_twitter.csv")
files['filePaths']
#files = files.values.tolist()

files

                                             filePaths
0    /Users/carlosarcila/Dropbox/Development/tripol...
1    /Users/carlosarcila/Dropbox/Development/tripol...
2    /Users/carlosarcila/Dropbox/Development/tripol...
3    /Users/carlosarcila/Dropbox/Development/tripol...
4    /Users/carlosarcila/Dropbox/Development/tripol...
..                                                 ...
134  /Users/carlosarcila/Dropbox/Development/tripol...
135  /Users/carlosarcila/Dropbox/Development/tripol...
136  /Users/carlosarcila/Dropbox/Development/tripol...
137  /Users/carlosarcila/Dropbox/Development/tripol...
138  /Users/carlosarcila/Dropbox/Development/tripol...

[139 rows x 1 columns]

In [34]:
csv_files = files['filePaths'].tolist()

li = []

for filename in csv_files:
    df = pd.read_csv(filename, index_col=None, header=0, sep=";")
    li.append(df)

twitter = pd.concat(li, axis=0, ignore_index=True)

In [35]:
twitter

,id,author_id,created_at,text,lang,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates
0,1479810682220646407,1578961946,2022-01-08T13:42:14.000Z,Lean el Evangelio de hoy 🙏 Sábado 8 de Enero 2...,es,13,19,109,0,NaN,NaN,NaN,NaN
1,1479444025396674572,1578961946,2022-01-07T13:25:17.000Z,Lean el Evangelio de hoy 🙏 Viernes 7 de Enero ...,es,19,34,84,2,NaN,NaN,NaN,NaN
2,1479084943254835210,1578961946,2022-01-06T13:38:25.000Z,Lean el Evangelio de hoy 🙏 Jueves 6 de Enero 2...,es,9,19,63,1,NaN,NaN,NaN,NaN
3,1478734972110446599,1578961946,2022-01-05T14:27:45.000Z,Lean el Evangelio de hoy 🙏 Miércoles 5 de Ener...,es,15,36,72,1,NaN,NaN,NaN,NaN
4,1478355299463536642,1578961946,2022-01-04T13:19:04.000Z,Lean el Evangelio de hoy 🙏 Martes 4 de Enero 2...,es,17,79,94,5,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,1278696351744897024,68740712,2020-07-02T14:25:41.000Z,Para reactivar la economía e iniciar la senda ...,es,332,322,833,25,NaN,NaN,NaN,NaN
243181,1278691070294069248,68740712,2020-07-02T14:04:42.000Z,El #COVID19 deja un impacto económico y social...,es,444,529,1327,39,NaN,NaN,NaN,NaN
243182,1278620087155646464,68740712,2020-07-02T09:22:39.000Z,A partir de las 13:00 horas estaré con Antonio...,es,266,825,785,83,NaN,NaN,NaN,NaN
243183,1278298948512382976,68740712,2020-07-01T12:06:33.000Z,"Siempre, también en las etapas más duras de la...",es,237,182,766,11,68740712.0,NaN,NaN,NaN
243184,1278298945752567808,68740712,2020-07-01T12:06:32.000Z,"Hoy, junto al primer ministro @antoniocostapm,...",es,492,1154,1651,120,NaN,NaN,NaN,NaN

In [36]:
twitter['author_id'].unique()

array([         1578961946,            25352511,  740226843589107712,
                 149991703,            54414081,            19722366,
                 555684585,           374115730,            24900072,
                  31133330,            77009449,          3092373641,
                 138814032,           339334958,           259681081,
                4515126989,          1618289516,          1381789998,
        814966194914652160,            60912608,           246971667,
                 123955962,           555147259,            24429981,
                1126723968,            27516672,           370275105,
                 418660662,            73981088,            45214422,
                2730306924,            42102939,           146542753,
                  20978436, 1097962618596327424, 1189235595341684740,
                  36392123,  932642995966500866, 1068848040834990082,
        717487948128731136,            14746456,            19472578,
                  51714305,  718009445863788544,            31237480,
                 599399505,           130537001,           270839361,
        920277002858500096,           419622371,           266674649,
                 331005596,           963938472,           403544693,
                2278995820,            18762875,            48062712,
        999578121123848192,            37621971,            31416615,
                 552561770,            83093494,           523386042,
                  19002571,            36626651,           158342368,
                  33884545,            58417540,           260788584,
                 122375549,           266669687,           378944786,
                 320682727,            68740712])

In [37]:
twitter['lang'].unique()

array(['es', 'und', 'fr', 'ca', 'it', 'nl', 'pt', 'sv', 'en', 'in', 'eu',
       'hi', 'lt', 'pl', 'tl', 'tr', 'de', 'da', 'ro', 'et', 'ht', 'sl',
       'fi', 'vi', 'cy', 'hu', 'ru', 'iw', 'is', 'no', 'lv', 'el', 'ar',
       'cs'], dtype=object)

In [38]:
len(twitter['author_id'].unique())

74

In [39]:
twitter[twitter['text'].isna()]

Empty DataFrame
Columns: [id, author_id, created_at, text, lang, public_metrics.retweet_count, public_metrics.reply_count, public_metrics.like_count, public_metrics.quote_count, in_reply_to_user_id, geo.place_id, geo.coordinates.type, geo.coordinates.coordinates]
Index: []

In [41]:
#twitter.loc[190752]

In [42]:
twitter.to_csv('twitter_database_tripol.csv', index=False)

# Join two datasets in one

In [77]:
twitter['media'] = 'Twitter'
twitter

,reference,author_id,created_at,text,lang,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,media,date
0,1479810682220646407,1578961946,2022-01-08T13:42:14.000Z,Lean el Evangelio de hoy 🙏 Sábado 8 de Enero 2...,es,13,19,109,0,NaN,NaN,NaN,NaN,Twitter,2022-01-08
1,1479444025396674572,1578961946,2022-01-07T13:25:17.000Z,Lean el Evangelio de hoy 🙏 Viernes 7 de Enero ...,es,19,34,84,2,NaN,NaN,NaN,NaN,Twitter,2022-01-07
2,1479084943254835210,1578961946,2022-01-06T13:38:25.000Z,Lean el Evangelio de hoy 🙏 Jueves 6 de Enero 2...,es,9,19,63,1,NaN,NaN,NaN,NaN,Twitter,2022-01-06
3,1478734972110446599,1578961946,2022-01-05T14:27:45.000Z,Lean el Evangelio de hoy 🙏 Miércoles 5 de Ener...,es,15,36,72,1,NaN,NaN,NaN,NaN,Twitter,2022-01-05
4,1478355299463536642,1578961946,2022-01-04T13:19:04.000Z,Lean el Evangelio de hoy 🙏 Martes 4 de Enero 2...,es,17,79,94,5,NaN,NaN,NaN,NaN,Twitter,2022-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,1278696351744897024,68740712,2020-07-02T14:25:41.000Z,Para reactivar la economía e iniciar la senda ...,es,332,322,833,25,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243181,1278691070294069248,68740712,2020-07-02T14:04:42.000Z,El #COVID19 deja un impacto económico y social...,es,444,529,1327,39,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243182,1278620087155646464,68740712,2020-07-02T09:22:39.000Z,A partir de las 13:00 horas estaré con Antonio...,es,266,825,785,83,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243183,1278298948512382976,68740712,2020-07-01T12:06:33.000Z,"Siempre, también en las etapas más duras de la...",es,237,182,766,11,68740712.0,NaN,NaN,NaN,Twitter,2020-07-01
243184,1278298945752567808,68740712,2020-07-01T12:06:32.000Z,"Hoy, junto al primer ministro @antoniocostapm,...",es,492,1154,1651,120,NaN,NaN,NaN,NaN,Twitter,2020-07-01

In [78]:
twitter['date']=twitter['created_at'].str[:10]
twitter

,reference,author_id,created_at,text,lang,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,media,date
0,1479810682220646407,1578961946,2022-01-08T13:42:14.000Z,Lean el Evangelio de hoy 🙏 Sábado 8 de Enero 2...,es,13,19,109,0,NaN,NaN,NaN,NaN,Twitter,2022-01-08
1,1479444025396674572,1578961946,2022-01-07T13:25:17.000Z,Lean el Evangelio de hoy 🙏 Viernes 7 de Enero ...,es,19,34,84,2,NaN,NaN,NaN,NaN,Twitter,2022-01-07
2,1479084943254835210,1578961946,2022-01-06T13:38:25.000Z,Lean el Evangelio de hoy 🙏 Jueves 6 de Enero 2...,es,9,19,63,1,NaN,NaN,NaN,NaN,Twitter,2022-01-06
3,1478734972110446599,1578961946,2022-01-05T14:27:45.000Z,Lean el Evangelio de hoy 🙏 Miércoles 5 de Ener...,es,15,36,72,1,NaN,NaN,NaN,NaN,Twitter,2022-01-05
4,1478355299463536642,1578961946,2022-01-04T13:19:04.000Z,Lean el Evangelio de hoy 🙏 Martes 4 de Enero 2...,es,17,79,94,5,NaN,NaN,NaN,NaN,Twitter,2022-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,1278696351744897024,68740712,2020-07-02T14:25:41.000Z,Para reactivar la economía e iniciar la senda ...,es,332,322,833,25,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243181,1278691070294069248,68740712,2020-07-02T14:04:42.000Z,El #COVID19 deja un impacto económico y social...,es,444,529,1327,39,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243182,1278620087155646464,68740712,2020-07-02T09:22:39.000Z,A partir de las 13:00 horas estaré con Antonio...,es,266,825,785,83,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243183,1278298948512382976,68740712,2020-07-01T12:06:33.000Z,"Siempre, también en las etapas más duras de la...",es,237,182,766,11,68740712.0,NaN,NaN,NaN,Twitter,2020-07-01
243184,1278298945752567808,68740712,2020-07-01T12:06:32.000Z,"Hoy, junto al primer ministro @antoniocostapm,...",es,492,1154,1651,120,NaN,NaN,NaN,NaN,Twitter,2020-07-01

In [79]:
twitter['date'] = pd.to_datetime(twitter['date'], format="%Y-%m-%d")

In [80]:
twitter.rename(columns= {'id':'reference' }, inplace=True)

In [81]:
twitter

,reference,author_id,created_at,text,lang,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,media,date
0,1479810682220646407,1578961946,2022-01-08T13:42:14.000Z,Lean el Evangelio de hoy 🙏 Sábado 8 de Enero 2...,es,13,19,109,0,NaN,NaN,NaN,NaN,Twitter,2022-01-08
1,1479444025396674572,1578961946,2022-01-07T13:25:17.000Z,Lean el Evangelio de hoy 🙏 Viernes 7 de Enero ...,es,19,34,84,2,NaN,NaN,NaN,NaN,Twitter,2022-01-07
2,1479084943254835210,1578961946,2022-01-06T13:38:25.000Z,Lean el Evangelio de hoy 🙏 Jueves 6 de Enero 2...,es,9,19,63,1,NaN,NaN,NaN,NaN,Twitter,2022-01-06
3,1478734972110446599,1578961946,2022-01-05T14:27:45.000Z,Lean el Evangelio de hoy 🙏 Miércoles 5 de Ener...,es,15,36,72,1,NaN,NaN,NaN,NaN,Twitter,2022-01-05
4,1478355299463536642,1578961946,2022-01-04T13:19:04.000Z,Lean el Evangelio de hoy 🙏 Martes 4 de Enero 2...,es,17,79,94,5,NaN,NaN,NaN,NaN,Twitter,2022-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,1278696351744897024,68740712,2020-07-02T14:25:41.000Z,Para reactivar la economía e iniciar la senda ...,es,332,322,833,25,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243181,1278691070294069248,68740712,2020-07-02T14:04:42.000Z,El #COVID19 deja un impacto económico y social...,es,444,529,1327,39,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243182,1278620087155646464,68740712,2020-07-02T09:22:39.000Z,A partir de las 13:00 horas estaré con Antonio...,es,266,825,785,83,NaN,NaN,NaN,NaN,Twitter,2020-07-02
243183,1278298948512382976,68740712,2020-07-01T12:06:33.000Z,"Siempre, también en las etapas más duras de la...",es,237,182,766,11,68740712.0,NaN,NaN,NaN,Twitter,2020-07-01
243184,1278298945752567808,68740712,2020-07-01T12:06:32.000Z,"Hoy, junto al primer ministro @antoniocostapm,...",es,492,1154,1651,120,NaN,NaN,NaN,NaN,Twitter,2020-07-01

In [82]:
df

,Unnamed: 0,text,date,media,country,reference,lang
0,0,"Siccome s’era capita l’aria, quel gran genio d...",2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it
1,1,E per essere interessante anziché riabilitato ...,2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it
0,0,di Giancarlo Mazzuca,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it
1,1,SOS giovani. Se il Covid ha continuato a prend...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it
2,2,Le cifre parlano chiaro perché in Italia oltre...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it
...,...,...,...,...,...,...,...
5,5,Quienes vivimos la Transición podemos dar test...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt,es
6,6,La frustración y fragmentación social provocad...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt,es
7,7,"Por lo demás, el acoso de la extrema derecha c...",2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt,es
8,8,En un ambiente así resultaría lógico poner un ...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt,es
9,9,Aunque me gustaría equivocarme en la predicció...,2021-05-03,EL PAIS,SP,SP_PAI_03_05_21_2A.txt,es

In [83]:
database = pd.concat([df, twitter])
database

,Unnamed: 0,text,date,media,country,reference,lang,author_id,created_at,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates
0,0,"Siccome s’era capita l’aria, quel gran genio d...",2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,E per essere interessante anziché riabilitato ...,2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,di Giancarlo Mazzuca,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,SOS giovani. Se il Covid ha continuato a prend...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Le cifre parlano chiaro perché in Italia oltre...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,NaN,Para reactivar la economía e iniciar la senda ...,2020-07-02,Twitter,NaN,1278696351744897024,es,68740712.0,2020-07-02T14:25:41.000Z,332.0,322.0,833.0,25.0,NaN,NaN,NaN,NaN
243181,NaN,El #COVID19 deja un impacto económico y social...,2020-07-02,Twitter,NaN,1278691070294069248,es,68740712.0,2020-07-02T14:04:42.000Z,444.0,529.0,1327.0,39.0,NaN,NaN,NaN,NaN
243182,NaN,A partir de las 13:00 horas estaré con Antonio...,2020-07-02,Twitter,NaN,1278620087155646464,es,68740712.0,2020-07-02T09:22:39.000Z,266.0,825.0,785.0,83.0,NaN,NaN,NaN,NaN
243183,NaN,"Siempre, también en las etapas más duras de la...",2020-07-01,Twitter,NaN,1278298948512382976,es,68740712.0,2020-07-01T12:06:33.000Z,237.0,182.0,766.0,11.0,68740712.0,NaN,NaN,NaN
243184,NaN,"Hoy, junto al primer ministro @antoniocostapm,...",2020-07-01,Twitter,NaN,1278298945752567808,es,68740712.0,2020-07-01T12:06:32.000Z,492.0,1154.0,1651.0,120.0,NaN,NaN,NaN,NaN

In [84]:
for col in database.columns:
    print(col)

Unnamed: 0
text
date
media
country
reference
lang
author_id
created_at
public_metrics.retweet_count
public_metrics.reply_count
public_metrics.like_count
public_metrics.quote_count
in_reply_to_user_id
geo.place_id
geo.coordinates.type
geo.coordinates.coordinates

In [85]:
database = database.drop('Unnamed: 0', axis=1)
database = database.drop('created_at', axis=1)
database

,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates
0,"Siccome s’era capita l’aria, quel gran genio d...",2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E per essere interessante anziché riabilitato ...,2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,di Giancarlo Mazzuca,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SOS giovani. Se il Covid ha continuato a prend...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Le cifre parlano chiaro perché in Italia oltre...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,Para reactivar la economía e iniciar la senda ...,2020-07-02,Twitter,NaN,1278696351744897024,es,68740712.0,332.0,322.0,833.0,25.0,NaN,NaN,NaN,NaN
243181,El #COVID19 deja un impacto económico y social...,2020-07-02,Twitter,NaN,1278691070294069248,es,68740712.0,444.0,529.0,1327.0,39.0,NaN,NaN,NaN,NaN
243182,A partir de las 13:00 horas estaré con Antonio...,2020-07-02,Twitter,NaN,1278620087155646464,es,68740712.0,266.0,825.0,785.0,83.0,NaN,NaN,NaN,NaN
243183,"Siempre, también en las etapas más duras de la...",2020-07-01,Twitter,NaN,1278298948512382976,es,68740712.0,237.0,182.0,766.0,11.0,68740712.0,NaN,NaN,NaN
243184,"Hoy, junto al primer ministro @antoniocostapm,...",2020-07-01,Twitter,NaN,1278298945752567808,es,68740712.0,492.0,1154.0,1651.0,120.0,NaN,NaN,NaN,NaN

In [86]:
database['lang'].value_counts()

es     224656
it      40651
pt      33503
und      8712
ca       7865
en       1465
eu        796
fr        340
ro         63
in         52
tl         33
ht         31
hu         20
de         20
lt         13
nl         11
et         10
cy          8
da          8
fi          8
sl          7
pl          7
lv          6
sv          6
tr          5
no          5
is          3
ru          2
cs          2
vi          2
iw          1
hi          1
ar          1
el          1
Name: lang, dtype: int64

In [87]:
database.to_csv('database_tripol.csv', index=False)
database.to_csv('database_tripol_index.csv', index=True)

In [88]:
database

,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates
0,"Siccome s’era capita l’aria, quel gran genio d...",2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E per essere interessante anziché riabilitato ...,2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,di Giancarlo Mazzuca,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SOS giovani. Se il Covid ha continuato a prend...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Le cifre parlano chiaro perché in Italia oltre...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243180,Para reactivar la economía e iniciar la senda ...,2020-07-02,Twitter,NaN,1278696351744897024,es,68740712.0,332.0,322.0,833.0,25.0,NaN,NaN,NaN,NaN
243181,El #COVID19 deja un impacto económico y social...,2020-07-02,Twitter,NaN,1278691070294069248,es,68740712.0,444.0,529.0,1327.0,39.0,NaN,NaN,NaN,NaN
243182,A partir de las 13:00 horas estaré con Antonio...,2020-07-02,Twitter,NaN,1278620087155646464,es,68740712.0,266.0,825.0,785.0,83.0,NaN,NaN,NaN,NaN
243183,"Siempre, también en las etapas más duras de la...",2020-07-01,Twitter,NaN,1278298948512382976,es,68740712.0,237.0,182.0,766.0,11.0,68740712.0,NaN,NaN,NaN
243184,"Hoy, junto al primer ministro @antoniocostapm,...",2020-07-01,Twitter,NaN,1278298945752567808,es,68740712.0,492.0,1154.0,1651.0,120.0,NaN,NaN,NaN,NaN

In [ ]:
## Databases of Twitter by countries

In [ ]:
#Spain

In [99]:
database = pd.read_csv('database_tripol_index.csv')
database

/Users/carlosarcila/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,5,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates
0,0,"Siccome s’era capita l’aria, quel gran genio d...",2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,E per essere interessante anziché riabilitato ...,2021-04-29,LA STAMPA,IT,IT_STA_29_04_21_3B.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,di Giancarlo Mazzuca,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,SOS giovani. Se il Covid ha continuato a prend...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Le cifre parlano chiaro perché in Italia oltre...,2021-01-25,IL SOLE 24 ORE,IT,IT_SOL_25_01_21_3A.txt,it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318309,318309,Para reactivar la economía e iniciar la senda ...,2020-07-02,Twitter,NaN,1278696351744897024,es,68740712.0,332.0,322.0,833.0,25.0,NaN,NaN,NaN,NaN
318310,318310,El #COVID19 deja un impacto económico y social...,2020-07-02,Twitter,NaN,1278691070294069248,es,68740712.0,444.0,529.0,1327.0,39.0,NaN,NaN,NaN,NaN
318311,318311,A partir de las 13:00 horas estaré con Antonio...,2020-07-02,Twitter,NaN,1278620087155646464,es,68740712.0,266.0,825.0,785.0,83.0,NaN,NaN,NaN,NaN
318312,318312,"Siempre, también en las etapas más duras de la...",2020-07-01,Twitter,NaN,1278298948512382976,es,68740712.0,237.0,182.0,766.0,11.0,68740712.0,NaN,NaN,NaN
318313,318313,"Hoy, junto al primer ministro @antoniocostapm,...",2020-07-01,Twitter,NaN,1278298945752567808,es,68740712.0,492.0,1154.0,1651.0,120.0,NaN,NaN,NaN,NaN

In [100]:
#SPAIN Twitter Country and Usernames


database.loc[(database['author_id'] == 83093494.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 83093494.0) , 'username'] = "@anaponton"

database.loc[(database['author_id'] == 122375549.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 122375549.0) , 'username'] = "@ArnaldoOtegi"

database.loc[(database['author_id'] == 33884545.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 33884545.0) , 'username'] = "@CNNEE"

database.loc[(database['author_id'] == 266669687.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 266669687.0) , 'username'] = "@euronewses"

database.loc[(database['author_id'] == 58417540.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 58417540.0) , 'username'] = "@desdelamoncloa"

database.loc[(database['author_id'] == 552561770.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 552561770.0) , 'username'] = "@InesArrimadas"

database.loc[(database['author_id'] == 320682727.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 320682727.0) , 'username'] = "@iurkullu"

database.loc[(database['author_id'] == 378944786.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 378944786.0) , 'username'] = "@joanbaldovi"

database.loc[(database['author_id'] == 19002571.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 19002571.0) , 'username'] = "@LauraBorras"

database.loc[(database['author_id'] == 31416615.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 31416615.0) , 'username'] = "@junqueras"

database.loc[(database['author_id'] == 523386042.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 523386042.0) , 'username'] = "@pablocasado_"

database.loc[(database['author_id'] == 158342368.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 158342368.0) , 'username'] = "@PabloIglesias"

database.loc[(database['author_id'] == 36626651.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 36626651.0) , 'username'] = "@Europarl_ES"

database.loc[(database['author_id'] == 68740712.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 68740712.0) , 'username'] = "@sanchezcastejon"

database.loc[(database['author_id'] == 260788584.0) , 'country'] = "SP"
database.loc[(database['author_id'] == 260788584.0) , 'username'] = "@Santi_ABASCAL"

In [101]:
SPAIN_total = database.loc[(database['media'] == "Twitter") & (database['country'] == "SP")]
SPAIN_total

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
203354,203354,"Avui, donant suport al Pacto Histórico Interna...",2022-01-07,Twitter,SP,1479527444424151042,ca,31416615.0,90.0,206.0,331.0,27.0,NaN,NaN,NaN,NaN,@junqueras
203355,203355,"Ens ha deixat Desmond Tutu, lluitador incansab...",2021-12-26,Twitter,SP,1475122103233957890,ca,31416615.0,83.0,201.0,525.0,27.0,NaN,NaN,NaN,NaN,@junqueras
203356,203356,"Un 25 de desembre de fa 88 anys, moria el pres...",2021-12-25,Twitter,SP,1474680714507468802,ca,31416615.0,72.0,126.0,282.0,15.0,NaN,NaN,NaN,NaN,@junqueras
203357,203357,Moltes gràcies a l'equip d'@AquiCuni per perme...,2021-12-24,Twitter,SP,1474336335565627393,ca,31416615.0,49.0,152.0,240.0,21.0,NaN,NaN,NaN,NaN,@junqueras
203358,203358,Tenim els primers pressupostos de la Generalit...,2021-12-23,Twitter,SP,1474075079575326730,ca,31416615.0,88.0,854.0,279.0,180.0,NaN,NaN,NaN,NaN,@junqueras
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318309,318309,Para reactivar la economía e iniciar la senda ...,2020-07-02,Twitter,SP,1278696351744897024,es,68740712.0,332.0,322.0,833.0,25.0,NaN,NaN,NaN,NaN,@sanchezcastejon
318310,318310,El #COVID19 deja un impacto económico y social...,2020-07-02,Twitter,SP,1278691070294069248,es,68740712.0,444.0,529.0,1327.0,39.0,NaN,NaN,NaN,NaN,@sanchezcastejon
318311,318311,A partir de las 13:00 horas estaré con Antonio...,2020-07-02,Twitter,SP,1278620087155646464,es,68740712.0,266.0,825.0,785.0,83.0,NaN,NaN,NaN,NaN,@sanchezcastejon
318312,318312,"Siempre, también en las etapas más duras de la...",2020-07-01,Twitter,SP,1278298948512382976,es,68740712.0,237.0,182.0,766.0,11.0,68740712.0,NaN,NaN,NaN,@sanchezcastejon
318313,318313,"Hoy, junto al primer ministro @antoniocostapm,...",2020-07-01,Twitter,SP,1278298945752567808,es,68740712.0,492.0,1154.0,1651.0,120.0,NaN,NaN,NaN,NaN,@sanchezcastejon

In [103]:
SPAIN_total['country'].value_counts()

SP    114960
Name: country, dtype: int64

In [107]:
SPAIN_total['lang'].value_counts()

es     100725
ca       7771
und      4613
eu        786
pt        394
en        326
fr        136
it         77
in         25
ro         20
ht         19
hu         16
et          6
nl          5
cy          5
lv          4
no          4
de          3
tl          3
da          3
pl          3
fi          3
sl          2
is          2
tr          2
sv          2
lt          2
cs          2
vi          1
Name: lang, dtype: int64

In [109]:
SPAIN_total = SPAIN_total.loc[SPAIN_total['lang'] == "es"]
SPAIN_total['lang'].value_counts()

es    100725
Name: lang, dtype: int64

In [110]:
SPAIN_total.to_csv('SPAIN_twitter.csv', index=False)

In [111]:
database = pd.read_csv('SPAIN_twitter.csv')
database

/Users/carlosarcila/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
0,203510,Siempre estaremos en la defensa de la libertad...,2021-02-08,Twitter,SP,1358786659878391812,es,31416615.0,104.0,88.0,440.0,15.0,NaN,NaN,NaN,NaN,@junqueras
1,203516,@obloque @Esquerra_ERC @anaponton Moitas graza...,2021-02-05,Twitter,SP,1357707572904656901,es,31416615.0,12.0,3.0,54.0,2.0,155544328.0,NaN,NaN,NaN,@junqueras
2,203615,Tudanca puso una moción de censura contra el G...,2022-01-09,Twitter,SP,1480303604758196228,es,552561770.0,97.0,16.0,213.0,4.0,NaN,NaN,NaN,NaN,@InesArrimadas
3,203616,En TV3 entrevistan a Otegi y “bromean” con agr...,2022-01-09,Twitter,SP,1480223236914925575,es,552561770.0,942.0,3650.0,2583.0,948.0,NaN,NaN,NaN,NaN,@InesArrimadas
4,203617,Qué gran día hemos compartido con los compañer...,2022-01-09,Twitter,SP,1480193351995596805,es,552561770.0,275.0,54.0,611.0,10.0,NaN,NaN,NaN,NaN,@InesArrimadas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100720,318309,Para reactivar la economía e iniciar la senda ...,2020-07-02,Twitter,SP,1278696351744897024,es,68740712.0,332.0,322.0,833.0,25.0,NaN,NaN,NaN,NaN,@sanchezcastejon
100721,318310,El #COVID19 deja un impacto económico y social...,2020-07-02,Twitter,SP,1278691070294069248,es,68740712.0,444.0,529.0,1327.0,39.0,NaN,NaN,NaN,NaN,@sanchezcastejon
100722,318311,A partir de las 13:00 horas estaré con Antonio...,2020-07-02,Twitter,SP,1278620087155646464,es,68740712.0,266.0,825.0,785.0,83.0,NaN,NaN,NaN,NaN,@sanchezcastejon
100723,318312,"Siempre, también en las etapas más duras de la...",2020-07-01,Twitter,SP,1278298948512382976,es,68740712.0,237.0,182.0,766.0,11.0,68740712.0,NaN,NaN,NaN,@sanchezcastejon
100724,318313,"Hoy, junto al primer ministro @antoniocostapm,...",2020-07-01,Twitter,SP,1278298945752567808,es,68740712.0,492.0,1154.0,1651.0,120.0,NaN,NaN,NaN,NaN,@sanchezcastejon

In [112]:
#Italy

In [114]:
database = pd.read_csv('database_tripol_index.csv')

/Users/carlosarcila/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,5,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [115]:
database.loc[(database['author_id'] == 2278995820.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 2278995820.0) , 'username'] = "@Montecitorio"

database.loc[(database['author_id'] == 419622371.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 419622371.0) , 'username'] = "@EnricoLetta"

database.loc[(database['author_id'] == 266674649.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 266674649.0) , 'username'] = "@euronewsit"

database.loc[(database['author_id'] == 37621971.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 37621971.0) , 'username'] = "@Europarl_IT"

database.loc[(database['author_id'] == 130537001.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 130537001.0) , 'username'] = "@GiorgiaMeloni"

database.loc[(database['author_id'] == 9.995781211238482e+17) , 'country'] = "IT"
database.loc[(database['author_id'] == 9.995781211238482e+17) , 'username'] = "@GiuseppeConteIT"

database.loc[(database['author_id'] == 963938472.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 963938472.0) , 'username'] = "@Palazzo_Chigi"

database.loc[(database['author_id'] == 18762875.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 18762875.0) , 'username'] = "@matteorenzi"

database.loc[(database['author_id'] == 270839361.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 270839361.0) , 'username'] = "@matteosalvinimi"

database.loc[(database['author_id'] == 331005596.0) , 'country'] = "IT"
database.loc[(database['author_id'] == 331005596.0) , 'username'] = "@robersperanza"

database.loc[(database['author_id'] == 9.202770028585e+17) , 'country'] = "IT"
database.loc[(database['author_id'] == 9.202770028585e+17) , 'username'] = "@berlusconi"

In [121]:
ITALY_total = database.loc[(database['media'] == "Twitter") & (database['country'] == "IT")]
ITALY_total

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
168694,168694,No ad un’Italia modello Cina.Fratelli d’Italia...,2022-01-08,Twitter,IT,1479875628337881088,it,130537001.0,455.0,624.0,2021.0,47.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
168695,168695,Norme confuse e contraddittorie: famiglie e im...,2022-01-08,Twitter,IT,1479850724573995012,it,130537001.0,164.0,403.0,993.0,15.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
168696,168696,Pienamente d’accordo con le parole del profess...,2022-01-08,Twitter,IT,1479818482212642816,it,130537001.0,472.0,500.0,2165.0,45.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
168697,168697,L’ennesimo scaricabarile sulle spalle di impre...,2022-01-08,Twitter,IT,1479779981299531782,it,130537001.0,163.0,376.0,986.0,22.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
168698,168698,Auguri ai nostri fratelli cristiani di rito gr...,2022-01-07,Twitter,IT,1479455467076309003,it,130537001.0,147.0,264.0,1150.0,9.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203349,203349,📎 Bilancio a lungo termine e piano per la ripr...,2020-07-03,Twitter,IT,1279044008401162240,it,37621971.0,2.0,1.0,5.0,0.0,NaN,NaN,NaN,NaN,@Europarl_IT
203350,203350,Oggi è la Giornata mondiale senza sacchetti di...,2020-07-03,Twitter,IT,1279032890072989697,it,37621971.0,21.0,11.0,37.0,4.0,NaN,NaN,NaN,NaN,@Europarl_IT
203351,203351,Immigrazione verso l'UE. Le cause dell'immigra...,2020-07-02,Twitter,IT,1278733200861335554,it,37621971.0,7.0,1.0,12.0,2.0,NaN,NaN,NaN,NaN,@Europarl_IT
203352,203352,"""La decisione della Presidente von der Leyen d...",2020-07-02,Twitter,IT,1278730203641122821,it,37621971.0,20.0,5.0,64.0,0.0,NaN,NaN,NaN,NaN,@Europarl_IT
203353,203353,"Oggi, #1luglio, la Germania ha assunto la pres...",2020-07-01,Twitter,IT,1278376075458985984,it,37621971.0,8.0,0.0,31.0,1.0,NaN,NaN,NaN,NaN,@Europarl_IT

In [122]:
ITALY_total['lang'].value_counts()

it     32381
en       441
und      374
fr       144
es       109
ro        39
ca        34
pt        32
in        13
de        10
ht         8
tl         5
fi         4
sl         4
sv         3
pl         3
cy         2
da         2
eu         2
hu         2
lv         2
ar         1
el         1
no         1
tr         1
iw         1
is         1
Name: lang, dtype: int64

In [124]:
ITALY_total = ITALY_total.loc[ITALY_total['lang'] == "it"]
ITALY_total['lang'].value_counts()

it    32381
Name: lang, dtype: int64

In [125]:
ITALY_total.to_csv('ITALY_twitter.csv', index=False)

In [126]:
database = pd.read_csv('ITALY_twitter.csv')
database

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
0,168694,No ad un’Italia modello Cina.Fratelli d’Italia...,2022-01-08,Twitter,IT,1479875628337881088,it,130537001.0,455.0,624.0,2021.0,47.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
1,168695,Norme confuse e contraddittorie: famiglie e im...,2022-01-08,Twitter,IT,1479850724573995012,it,130537001.0,164.0,403.0,993.0,15.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
2,168696,Pienamente d’accordo con le parole del profess...,2022-01-08,Twitter,IT,1479818482212642816,it,130537001.0,472.0,500.0,2165.0,45.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
3,168697,L’ennesimo scaricabarile sulle spalle di impre...,2022-01-08,Twitter,IT,1479779981299531782,it,130537001.0,163.0,376.0,986.0,22.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
4,168698,Auguri ai nostri fratelli cristiani di rito gr...,2022-01-07,Twitter,IT,1479455467076309003,it,130537001.0,147.0,264.0,1150.0,9.0,NaN,NaN,NaN,NaN,@GiorgiaMeloni
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32376,203349,📎 Bilancio a lungo termine e piano per la ripr...,2020-07-03,Twitter,IT,1279044008401162240,it,37621971.0,2.0,1.0,5.0,0.0,NaN,NaN,NaN,NaN,@Europarl_IT
32377,203350,Oggi è la Giornata mondiale senza sacchetti di...,2020-07-03,Twitter,IT,1279032890072989697,it,37621971.0,21.0,11.0,37.0,4.0,NaN,NaN,NaN,NaN,@Europarl_IT
32378,203351,Immigrazione verso l'UE. Le cause dell'immigra...,2020-07-02,Twitter,IT,1278733200861335554,it,37621971.0,7.0,1.0,12.0,2.0,NaN,NaN,NaN,NaN,@Europarl_IT
32379,203352,"""La decisione della Presidente von der Leyen d...",2020-07-02,Twitter,IT,1278730203641122821,it,37621971.0,20.0,5.0,64.0,0.0,NaN,NaN,NaN,NaN,@Europarl_IT
32380,203353,"Oggi, #1luglio, la Germania ha assunto la pres...",2020-07-01,Twitter,IT,1278376075458985984,it,37621971.0,8.0,0.0,31.0,1.0,NaN,NaN,NaN,NaN,@Europarl_IT

In [ ]:
##PORTUGAL

In [127]:
database = pd.read_csv('database_tripol_index.csv')

/Users/carlosarcila/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,5,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [128]:
database.loc[(database['author_id'] == 1.0979626185963274e+18) , 'country'] = "PT"
database.loc[(database['author_id'] == 1.0979626185963274e+18) , 'username'] = "@AndreCVentura"

database.loc[(database['author_id'] == 7.180094458637885e+17) , 'country'] = "PT"
database.loc[(database['author_id'] == 7.180094458637885e+17) , 'username'] = "@antoniocostapm"

database.loc[(database['author_id'] == 19472578.0) , 'country'] = "PT"
database.loc[(database['author_id'] == 19472578.0) , 'username'] = "@catarina_mart"

database.loc[(database['author_id'] == 599399505.0) , 'country'] = "PT"
database.loc[(database['author_id'] == 599399505.0) , 'username'] = "@DGSaude"

database.loc[(database['author_id'] == 7.174879481287311e+17) , 'country'] = "PT"
database.loc[(database['author_id'] == 7.174879481287311e+17) , 'username'] = "@francisco__rs"

database.loc[(database['author_id'] == 1.1892355953416847e+18) , 'country'] = "PT"
database.loc[(database['author_id'] == 1.1892355953416847e+18) , 'username'] = "@jcf_liberal"

database.loc[(database['author_id'] == 51714305.0) , 'country'] = "PT"
database.loc[(database['author_id'] == 51714305.0) , 'username'] = "@Partido_PAN"

database.loc[(database['author_id'] == 36392123.0) , 'country'] = "PT"
database.loc[(database['author_id'] == 36392123.0) , 'username'] = "@pcp_pt"

database.loc[(database['author_id'] == 20978436.0) , 'country'] = "PT"
database.loc[(database['author_id'] == 20978436.0) , 'username'] = "@OsVerdes"

database.loc[(database['author_id'] == 9.326429959665009e+17) , 'country'] = "PT"
database.loc[(database['author_id'] == 9.326429959665009e+17) , 'username'] = "@govpt"

database.loc[(database['author_id'] == 7.180094458637885e+17) , 'country'] = "PT"
database.loc[(database['author_id'] == 7.180094458637885e+17) , 'username'] = "@GovernoMadeira"

database.loc[(database['author_id'] == 1.06884804083499e+18) , 'country'] = "PT"
database.loc[(database['author_id'] == 1.06884804083499e+18) , 'username'] = "@RuiRioPSD"

database.loc[(database['author_id'] == 14746456.0) , 'country'] = "PT"
database.loc[(database['author_id'] == 14746456.0) , 'username'] = "@ruitavares"

In [129]:
PORTUGAL_total = database.loc[(database['media'] == "Twitter") & (database['country'] == "PT")]
PORTUGAL_total

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
152266,152266,Não encontrando neste OE resposta robustas aos...,2021-10-27,Twitter,PT,1453391698684522507,pt,20978436.0,4.0,1.0,36.0,1.0,NaN,NaN,NaN,NaN,@OsVerdes
152267,152267,OE 2022Se não é quando a economia cresce que s...,2021-10-27,Twitter,PT,1453391322417672200,pt,20978436.0,7.0,0.0,22.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
152268,152268,Orçamento de Estado 2022- Saúde Mental Não est...,2021-10-27,Twitter,PT,1453335573012287492,pt,20978436.0,1.0,0.0,8.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
152269,152269,Orçamento de Estado 2022- Propostas offshores ...,2021-10-27,Twitter,PT,1453304756844302336,pt,20978436.0,2.0,0.0,10.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
152270,152270,Orçamento de Estado 2022Quantas vezes ouvimos ...,2021-10-26,Twitter,PT,1453038514635948038,pt,20978436.0,5.0,0.0,21.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168689,168689,☀️ Mantenha-se hidratado e protegido do calor....,2020-07-04,Twitter,PT,1279407587214139393,pt,599399505.0,4.0,0.0,16.0,0.0,NaN,NaN,NaN,NaN,@DGSaude
168690,168690,Já se encontra disponível o relatório de situa...,2020-07-03,Twitter,PT,1279128188434755584,pt,599399505.0,5.0,7.0,26.0,11.0,NaN,NaN,NaN,NaN,@DGSaude
168691,168691,"""All we need is love!"" Está nas tuas mãos ajud...",2020-07-02,Twitter,PT,1278741353787162626,pt,599399505.0,6.0,3.0,29.0,2.0,NaN,NaN,NaN,NaN,@DGSaude
168692,168692,Já se encontra disponível o relatório de situa...,2020-07-02,Twitter,PT,1278687927455961090,pt,599399505.0,6.0,4.0,29.0,1.0,NaN,NaN,NaN,NaN,@DGSaude
168693,168693,Saiba os cuidados a ter para a correta utiliza...,2020-07-02,Twitter,PT,1278624585555025920,pt,599399505.0,7.0,0.0,15.0,1.0,NaN,NaN,NaN,NaN,@DGSaude

In [131]:
PORTUGAL_total['lang'].value_counts()

pt     13340
en       566
und      460
es        60
fr        41
ca         7
it         7
de         5
ru         2
hu         2
da         1
tr         1
tl         1
ro         1
Name: lang, dtype: int64

In [132]:
PORTUGAL_total = PORTUGAL_total.loc[PORTUGAL_total['lang'] == "pt"]
PORTUGAL_total['lang'].value_counts()

pt    13340
Name: lang, dtype: int64

In [133]:
PORTUGAL_total.to_csv('PORTUGAL_twitter.csv', index=False)

In [134]:
database = pd.read_csv('PORTUGAL_twitter.csv')
database

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
0,152266,Não encontrando neste OE resposta robustas aos...,2021-10-27,Twitter,PT,1453391698684522507,pt,20978436.0,4.0,1.0,36.0,1.0,NaN,NaN,NaN,NaN,@OsVerdes
1,152267,OE 2022Se não é quando a economia cresce que s...,2021-10-27,Twitter,PT,1453391322417672200,pt,20978436.0,7.0,0.0,22.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
2,152268,Orçamento de Estado 2022- Saúde Mental Não est...,2021-10-27,Twitter,PT,1453335573012287492,pt,20978436.0,1.0,0.0,8.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
3,152269,Orçamento de Estado 2022- Propostas offshores ...,2021-10-27,Twitter,PT,1453304756844302336,pt,20978436.0,2.0,0.0,10.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
4,152270,Orçamento de Estado 2022Quantas vezes ouvimos ...,2021-10-26,Twitter,PT,1453038514635948038,pt,20978436.0,5.0,0.0,21.0,0.0,NaN,NaN,NaN,NaN,@OsVerdes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13335,168689,☀️ Mantenha-se hidratado e protegido do calor....,2020-07-04,Twitter,PT,1279407587214139393,pt,599399505.0,4.0,0.0,16.0,0.0,NaN,NaN,NaN,NaN,@DGSaude
13336,168690,Já se encontra disponível o relatório de situa...,2020-07-03,Twitter,PT,1279128188434755584,pt,599399505.0,5.0,7.0,26.0,11.0,NaN,NaN,NaN,NaN,@DGSaude
13337,168691,"""All we need is love!"" Está nas tuas mãos ajud...",2020-07-02,Twitter,PT,1278741353787162626,pt,599399505.0,6.0,3.0,29.0,2.0,NaN,NaN,NaN,NaN,@DGSaude
13338,168692,Já se encontra disponível o relatório de situa...,2020-07-02,Twitter,PT,1278687927455961090,pt,599399505.0,6.0,4.0,29.0,1.0,NaN,NaN,NaN,NaN,@DGSaude
13339,168693,Saiba os cuidados a ter para a correta utiliza...,2020-07-02,Twitter,PT,1278624585555025920,pt,599399505.0,7.0,0.0,15.0,1.0,NaN,NaN,NaN,NaN,@DGSaude

In [ ]:
#CHILE

In [135]:
database = pd.read_csv('database_tripol_index.csv')

/Users/carlosarcila/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,5,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [136]:
database.loc[(database['author_id'] == 60912608.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 60912608.0) , 'username'] = "@Camara_cl"

database.loc[(database['author_id'] == 1126723968.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 1126723968.0) , 'username'] = "@MaldonadoCurti"

database.loc[(database['author_id'] == 146542753.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 146542753.0) , 'username'] = "@danieljadue"

database.loc[(database['author_id'] == 370275105.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 370275105.0) , 'username'] = "@evelynmatthei'"

database.loc[(database['author_id'] == 73981088.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 73981088.0) , 'username'] = "@gabrielboric'"

database.loc[(database['author_id'] == 42102939.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 42102939.0) , 'username'] = "@GobiernodeChile"

database.loc[(database['author_id'] == 246971667.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 246971667.0) , 'username'] = "@HeraldoMunoz"

database.loc[(database['author_id'] == 1618289516.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 1618289516.0) , 'username'] = "@ignaciobriones_"

database.loc[(database['author_id'] == 555147259.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 555147259.0) , 'username'] = "@LavinJoaquin"

database.loc[(database['author_id'] == 123955962.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 123955962.0) , 'username'] = "@joseantoniokast"

database.loc[(database['author_id'] == 45214422.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 45214422.0) , 'username'] = "@desbordes"

database.loc[(database['author_id'] == 1381789998.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 1381789998.0) , 'username'] = "@PamJiles"

database.loc[(database['author_id'] == 8.149661949146522e+17) , 'country'] = "CH"
database.loc[(database['author_id'] == 8.149661949146522e+17) , 'username'] = "@paulanarvaezo"

database.loc[(database['author_id'] == 24429981.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 24429981.0) , 'username'] = "@sebastiansichel"

database.loc[(database['author_id'] == 418660662.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 418660662.0) , 'username'] = "@Senado_Chile"

database.loc[(database['author_id'] == 27516672.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 27516672.0) , 'username'] = "@ximerincon"

database.loc[(database['author_id'] == 2730306924.0) , 'country'] = "CH"
database.loc[(database['author_id'] == 2730306924.0) , 'username'] = "@ProvosteYasna"

In [137]:
CHILE_total = database.loc[(database['media'] == "Twitter") & (database['country'] == "CH")]
CHILE_total

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
102794,102794,@alonsurbod Sin duda,2022-01-08,Twitter,CH,1479924207584641027,es,1.618290e+09,0.0,0.0,0.0,0.0,1.785415e+08,NaN,NaN,NaN,@ignaciobriones_
102795,102795,@JuanoMcJuano ?,2022-01-08,Twitter,CH,1479918550567374848,und,1.618290e+09,0.0,2.0,0.0,0.0,1.716371e+08,NaN,NaN,NaN,@ignaciobriones_
102796,102796,@PanxoAlienwareZ No. Esa información que ud se...,2022-01-08,Twitter,CH,1479918338528538630,es,1.618290e+09,0.0,0.0,8.0,0.0,2.627889e+07,NaN,NaN,NaN,@ignaciobriones_
102797,102797,La constitución es un pacto intergeneracional....,2022-01-08,Twitter,CH,1479819571599085568,es,1.618290e+09,142.0,45.0,676.0,18.0,NaN,NaN,NaN,NaN,@ignaciobriones_
102798,102798,Sigue el parlamentarismo de facto de la oposic...,2022-01-06,Twitter,CH,1478910655373611008,es,1.618290e+09,234.0,68.0,875.0,15.0,NaN,NaN,NaN,NaN,@ignaciobriones_
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152261,152261,@milalywood Puedo ofrecer toda mi capacidad y ...,2020-07-01,Twitter,CH,1278354284057366528,es,1.465428e+08,4.0,3.0,16.0,0.0,8.380073e+17,NaN,NaN,NaN,@danieljadue
152262,152262,@milalywood Ud renunciaría a ser quien es para...,2020-07-01,Twitter,CH,1278353581234585600,es,1.465428e+08,0.0,1.0,6.0,1.0,8.380073e+17,NaN,NaN,NaN,@danieljadue
152263,152263,@GZiga Me puede dar un teléfono cómo ubicarlo ...,2020-07-01,Twitter,CH,1278344699435257858,es,1.465428e+08,0.0,0.0,1.0,0.0,3.564497e+08,NaN,NaN,NaN,@danieljadue
152264,152264,@_MarinaRos Ningún país con una política exter...,2020-07-01,Twitter,CH,1278342039332061184,es,1.465428e+08,3.0,4.0,12.0,0.0,1.100351e+18,NaN,NaN,NaN,@danieljadue
152265,152265,Hoy estaremos nuevamente en “Una conversación ...,2020-07-01,Twitter,CH,1278338422185299974,es,1.465428e+08,219.0,57.0,739.0,5.0,NaN,NaN,NaN,NaN,@danieljadue

In [138]:
CHILE_total['lang'].value_counts()

es     47049
und     2028
pt       121
en       115
ca        45
tl        24
it        19
fr        14
in        13
lt        11
eu         8
nl         5
ht         4
et         4
da         2
de         2
fi         1
sl         1
vi         1
cy         1
hi         1
tr         1
ro         1
pl         1
Name: lang, dtype: int64

In [139]:
CHILE_total = CHILE_total.loc[CHILE_total['lang'] == "es"]
CHILE_total['lang'].value_counts()

es    47049
Name: lang, dtype: int64

In [140]:
CHILE_total.to_csv('CHILE_twitter.csv', index=False)

In [141]:
database = pd.read_csv('CHILE_twitter.csv')
database

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
0,102794,@alonsurbod Sin duda,2022-01-08,Twitter,CH,1479924207584641027,es,1.618290e+09,0.0,0.0,0.0,0.0,1.785415e+08,NaN,NaN,NaN,@ignaciobriones_
1,102796,@PanxoAlienwareZ No. Esa información que ud se...,2022-01-08,Twitter,CH,1479918338528538630,es,1.618290e+09,0.0,0.0,8.0,0.0,2.627889e+07,NaN,NaN,NaN,@ignaciobriones_
2,102797,La constitución es un pacto intergeneracional....,2022-01-08,Twitter,CH,1479819571599085568,es,1.618290e+09,142.0,45.0,676.0,18.0,NaN,NaN,NaN,NaN,@ignaciobriones_
3,102798,Sigue el parlamentarismo de facto de la oposic...,2022-01-06,Twitter,CH,1478910655373611008,es,1.618290e+09,234.0,68.0,875.0,15.0,NaN,NaN,NaN,NaN,@ignaciobriones_
4,102799,@JamesMc55748917 Muchas gracias James. Lo mism...,2022-01-03,Twitter,CH,1478060535660822528,es,1.618290e+09,0.0,0.0,0.0,0.0,1.241795e+18,NaN,NaN,NaN,@ignaciobriones_
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47044,152261,@milalywood Puedo ofrecer toda mi capacidad y ...,2020-07-01,Twitter,CH,1278354284057366528,es,1.465428e+08,4.0,3.0,16.0,0.0,8.380073e+17,NaN,NaN,NaN,@danieljadue
47045,152262,@milalywood Ud renunciaría a ser quien es para...,2020-07-01,Twitter,CH,1278353581234585600,es,1.465428e+08,0.0,1.0,6.0,1.0,8.380073e+17,NaN,NaN,NaN,@danieljadue
47046,152263,@GZiga Me puede dar un teléfono cómo ubicarlo ...,2020-07-01,Twitter,CH,1278344699435257858,es,1.465428e+08,0.0,0.0,1.0,0.0,3.564497e+08,NaN,NaN,NaN,@danieljadue
47047,152264,@_MarinaRos Ningún país con una política exter...,2020-07-01,Twitter,CH,1278342039332061184,es,1.465428e+08,3.0,4.0,12.0,0.0,1.100351e+18,NaN,NaN,NaN,@danieljadue
47048,152265,Hoy estaremos nuevamente en “Una conversación ...,2020-07-01,Twitter,CH,1278338422185299974,es,1.465428e+08,219.0,57.0,739.0,5.0,NaN,NaN,NaN,NaN,@danieljadue

In [ ]:
#ARGENTINA

In [142]:
database = pd.read_csv('database_tripol_index.csv')

/Users/carlosarcila/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,5,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [143]:
database.loc[(database['author_id'] == 149991703.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 149991703.0) , 'username'] = "@alferdez"

database.loc[(database['author_id'] == 3092373641.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 3092373641.0) , 'username'] = "@alfredocornejo"

database.loc[(database['author_id'] == 259681081.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 259681081.0) , 'username'] = "@AntonioBonfatti"

database.loc[(database['author_id'] == 7.402268435891077e+17) , 'country'] = "AR"
database.loc[(database['author_id'] == 7.402268435891077e+17) , 'username'] = "@DiputadosAR"

database.loc[(database['author_id'] == 138814032.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 138814032.0) , 'username'] = "@CFKArgentina"

database.loc[(database['author_id'] == 31133330.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 31133330.0) , 'username'] = "@danielscioli"

database.loc[(database['author_id'] == 1578961946.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 1578961946.0) , 'username'] = "@elisacarrio"

database.loc[(database['author_id'] == 339334958.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 339334958.0) , 'username'] = "@GerardoMorales"

database.loc[(database['author_id'] == 4515126989.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 4515126989.0) , 'username'] = "@CasaRosada"

database.loc[(database['author_id'] == 77009449.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 77009449.0) , 'username'] = "@horaciorlarreta"

database.loc[(database['author_id'] == 19722366.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 19722366.0) , 'username'] = "@joseluisgioja"

database.loc[(database['author_id'] == 24900072.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 24900072.0) , 'username'] = "@mauriciomacri"

database.loc[(database['author_id'] == 374115730.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 374115730.0) , 'username'] = "@NicolasdelCano"

database.loc[(database['author_id'] == 54414081.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 54414081.0) , 'username'] = "@PatoBullrich"

database.loc[(database['author_id'] == 555684585.0) , 'country'] = "AR"
database.loc[(database['author_id'] == 555684585.0) , 'username'] = "@SenadoArgentina"

In [144]:
ARGENTINA_total = database.loc[(database['media'] == "Twitter") & (database['country'] == "AR")]
ARGENTINA_total

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
75129,75129,Lean el Evangelio de hoy 🙏 Sábado 8 de Enero 2...,2022-01-08,Twitter,AR,1479810682220646407,es,1.578962e+09,13.0,19.0,109.0,0.0,NaN,NaN,NaN,NaN,@elisacarrio
75130,75130,Lean el Evangelio de hoy 🙏 Viernes 7 de Enero ...,2022-01-07,Twitter,AR,1479444025396674572,es,1.578962e+09,19.0,34.0,84.0,2.0,NaN,NaN,NaN,NaN,@elisacarrio
75131,75131,Lean el Evangelio de hoy 🙏 Jueves 6 de Enero 2...,2022-01-06,Twitter,AR,1479084943254835210,es,1.578962e+09,9.0,19.0,63.0,1.0,NaN,NaN,NaN,NaN,@elisacarrio
75132,75132,Lean el Evangelio de hoy 🙏 Miércoles 5 de Ener...,2022-01-05,Twitter,AR,1478734972110446599,es,1.578962e+09,15.0,36.0,72.0,1.0,NaN,NaN,NaN,NaN,@elisacarrio
75133,75133,Lean el Evangelio de hoy 🙏 Martes 4 de Enero 2...,2022-01-04,Twitter,AR,1478355299463536642,es,1.578962e+09,17.0,79.0,94.0,5.0,NaN,NaN,NaN,NaN,@elisacarrio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102789,102789,EN VIVO | Reporte diario desde el Ministerio d...,2020-07-02,Twitter,AR,1278661537209688072,es,4.515127e+09,85.0,13.0,185.0,6.0,NaN,NaN,NaN,NaN,@CasaRosada
102790,102790,El Gobierno renovó el programa Ahora 12 hasta ...,2020-07-01,Twitter,AR,1278474223305048065,es,4.515127e+09,145.0,18.0,345.0,5.0,NaN,NaN,NaN,NaN,@CasaRosada
102791,102791,El Gobierno extendió hasta el 30 de agosto la ...,2020-07-01,Twitter,AR,1278424134423384068,es,4.515127e+09,61.0,8.0,137.0,4.0,NaN,NaN,NaN,NaN,@CasaRosada
102792,102792,"El Gobierno implementó el programa Detectar, u...",2020-07-01,Twitter,AR,1278361897105063936,es,4.515127e+09,48.0,7.0,121.0,2.0,NaN,NaN,NaN,NaN,@CasaRosada
102793,102793,EN VIVO | Reporte diario desde el Ministerio d...,2020-07-01,Twitter,AR,1278298664583286784,es,4.515127e+09,95.0,13.0,141.0,5.0,NaN,NaN,NaN,NaN,@CasaRosada

In [145]:
ARGENTINA_total['lang'].value_counts()

es     26308
und     1224
pt        10
en         5
it         5
ca         5
fr         5
in         1
nl         1
sv         1
Name: lang, dtype: int64

In [146]:
ARGENTINA_total = ARGENTINA_total.loc[ARGENTINA_total['lang'] == "es"]
ARGENTINA_total['lang'].value_counts()

es    26308
Name: lang, dtype: int64

In [147]:
ARGENTINA_total.to_csv('ARGENTINA_twitter.csv', index=False)

In [148]:
database = pd.read_csv('ARGENTINA_twitter.csv')
database

,index,text,date,media,country,reference,lang,author_id,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,in_reply_to_user_id,geo.place_id,geo.coordinates.type,geo.coordinates.coordinates,username
0,75129,Lean el Evangelio de hoy 🙏 Sábado 8 de Enero 2...,2022-01-08,Twitter,AR,1479810682220646407,es,1.578962e+09,13.0,19.0,109.0,0.0,NaN,NaN,NaN,NaN,@elisacarrio
1,75130,Lean el Evangelio de hoy 🙏 Viernes 7 de Enero ...,2022-01-07,Twitter,AR,1479444025396674572,es,1.578962e+09,19.0,34.0,84.0,2.0,NaN,NaN,NaN,NaN,@elisacarrio
2,75131,Lean el Evangelio de hoy 🙏 Jueves 6 de Enero 2...,2022-01-06,Twitter,AR,1479084943254835210,es,1.578962e+09,9.0,19.0,63.0,1.0,NaN,NaN,NaN,NaN,@elisacarrio
3,75132,Lean el Evangelio de hoy 🙏 Miércoles 5 de Ener...,2022-01-05,Twitter,AR,1478734972110446599,es,1.578962e+09,15.0,36.0,72.0,1.0,NaN,NaN,NaN,NaN,@elisacarrio
4,75133,Lean el Evangelio de hoy 🙏 Martes 4 de Enero 2...,2022-01-04,Twitter,AR,1478355299463536642,es,1.578962e+09,17.0,79.0,94.0,5.0,NaN,NaN,NaN,NaN,@elisacarrio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26303,102789,EN VIVO | Reporte diario desde el Ministerio d...,2020-07-02,Twitter,AR,1278661537209688072,es,4.515127e+09,85.0,13.0,185.0,6.0,NaN,NaN,NaN,NaN,@CasaRosada
26304,102790,El Gobierno renovó el programa Ahora 12 hasta ...,2020-07-01,Twitter,AR,1278474223305048065,es,4.515127e+09,145.0,18.0,345.0,5.0,NaN,NaN,NaN,NaN,@CasaRosada
26305,102791,El Gobierno extendió hasta el 30 de agosto la ...,2020-07-01,Twitter,AR,1278424134423384068,es,4.515127e+09,61.0,8.0,137.0,4.0,NaN,NaN,NaN,NaN,@CasaRosada
26306,102792,"El Gobierno implementó el programa Detectar, u...",2020-07-01,Twitter,AR,1278361897105063936,es,4.515127e+09,48.0,7.0,121.0,2.0,NaN,NaN,NaN,NaN,@CasaRosada
26307,102793,EN VIVO | Reporte diario desde el Ministerio d...,2020-07-01,Twitter,AR,1278298664583286784,es,4.515127e+09,95.0,13.0,141.0,5.0,NaN,NaN,NaN,NaN,@CasaRosada